--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-14-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENCIA
--------------------------------------------------------

  CREATE TABLE "DEIVY1"."AGENCIA" 
   (	"CODAGEN" NUMBER(4,0), 
	"DIRAGEN" VARCHAR2(30 BYTE), 
	"RUCAGEN" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DEIVY1.AGENCIA
SET DEFINE OFF;
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('1','urb PRIMAVERA','10015511111');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('2','San Agustin','10015511112');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('3','LOS REYES','10015511113');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('4','urb PRIMAVERA','10015511114');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('5','San Agustin','10015511115');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('6','LOS REYES','10015511116');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('7','urb PRIMAVERA','10015511117');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('8','San Agustin','10015511118');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('9','LOS REYES','10015511119');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('10','urb PRIMAVERA','10015511120');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('11','San Agustin','10015511121');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('12','LOS REYES','10015511122');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('13','urb PRIMAVERA','10015511123');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('14','San Agustin','10015511124');
Insert into DEIVY1.AGENCIA (CODAGEN,DIRAGEN,RUCAGEN) values ('15','LOS REYES','10015511125');
--------------------------------------------------------
--  DDL for Index AGENCIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEIVY1"."AGENCIA_PK" ON "DEIVY1"."AGENCIA" ("CODAGEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AGENCIA
--------------------------------------------------------

  ALTER TABLE "DEIVY1"."AGENCIA" ADD CONSTRAINT "AGENCIA_PK" PRIMARY KEY ("CODAGEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEIVY1"."AGENCIA" MODIFY ("RUCAGEN" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."AGENCIA" MODIFY ("CODAGEN" NOT NULL ENABLE);
