--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-14-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROPIETARIO
--------------------------------------------------------

  CREATE TABLE "DEIVY1"."PROPIETARIO" 
   (	"CODPROP" NUMBER(4,0), 
	"NOMPROP" VARCHAR2(20 BYTE), 
	"APEPAPROP" VARCHAR2(30 BYTE), 
	"APEMAPROP" VARCHAR2(30 BYTE), 
	"DNIPROP" NUMBER(8,0), 
	"TELCONTPROP" NUMBER(9,0), 
	"DIRPROP" VARCHAR2(40 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DEIVY1.PROPIETARIO
SET DEFINE OFF;
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('1','LUIS','SANCHEZ','CORONADO','78455412','951654789','SAN VICENTE CAÑETE','luis.sanchez@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('2','DAYANA','AUDANTE','SOTO','74565815','963852741','SAN LUIS CAÑETE','DAYANA.AUDANTE@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('3','GIANELA','CORONADO','DE LA CRUZ','75655845','987654321','SAN VICENTE CAÑETE','GIANELA.CORONADO@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('4','ROSA','CUBILLA','BARRIOS','72655813','951623847','SAN LUIS CAÑETE','ROSA.CUBILLA@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('5','EDUARDO','SANCHEZ','CHACALIAZA','75489631','965874123','SAN VICENTE CAÑETE','EDUARDO.SANCHEZ@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('6','KAREN','LOPEZ','LUYO','74986515','965874321','IMPERIAL CAÑETE','KAREN.LOPEZ@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('7','FERNANDO','BARRAZA','AVALOS','75484965','987564951','SAN VICENTE CAÑETE','FERNANDO.BARRAZA@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('8','JESUS','CUBILLA','HHUAMAN','72158546','951654753','SAN LUIS CAÑETE','JESUS.CUBILLA@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('9','EMILIO','CANALES','CONDORI','75159546','953751486','SAN VICENTE CAÑETE','EMILIO.CANALES@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('10','JOSE','CASAS','ANCAJIMA','72655914','951684327','IMPERIAL CAÑETE','JOSE.CASAS@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('11','CARLOS','BENAVENTE','LOPEZ','75655215','965324187','SAN VICENTE CAÑETE','CARLOS.BENAVENTE@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('12','BRYAN','TORRES','SANCHEZ','74655815','985214763','SAN LUIS CAÑETE','BRYAN.TORRES@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('13','JAMES','SOTO','QUISPE','79746514','956321874','SAN VICENTE CAÑETE','JAMES.SOTO@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('14','JUAN','CANDELA','NAPAN','73211548','954126387','IMPERIAL CAÑETE','JUAN.CANDELA@hotmail.com');
Insert into DEIVY1.PROPIETARIO (CODPROP,NOMPROP,APEPAPROP,APEMAPROP,DNIPROP,TELCONTPROP,DIRPROP,EMAIL) values ('15','DAGNE','HUAMAN','CANALES','79655814','956632541','SAN VICENTE CAÑETE','DAGNE.HUAMAN@hotmail.com');
--------------------------------------------------------
--  DDL for Index PROPIETARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEIVY1"."PROPIETARIO_PK" ON "DEIVY1"."PROPIETARIO" ("CODPROP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PROPIETARIO
--------------------------------------------------------

  ALTER TABLE "DEIVY1"."PROPIETARIO" ADD CONSTRAINT "PROPIETARIO_PK" PRIMARY KEY ("CODPROP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEIVY1"."PROPIETARIO" MODIFY ("DNIPROP" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."PROPIETARIO" MODIFY ("APEMAPROP" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."PROPIETARIO" MODIFY ("APEPAPROP" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."PROPIETARIO" MODIFY ("NOMPROP" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."PROPIETARIO" MODIFY ("CODPROP" NOT NULL ENABLE);
