--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-14-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALQUILER
--------------------------------------------------------

  CREATE TABLE "DEIVY1"."ALQUILER" 
   (	"CODALQ" NUMBER(4,0), 
	"FIANALQ" NUMBER(6,2), 
	"FECFIRM" DATE, 
	"FECINI" DATE, 
	"FECFIN" DATE, 
	"CODINQ" NUMBER(4,0), 
	"CODVIV" NUMBER(4,0), 
	"IMPMENS" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DEIVY1.ALQUILER
SET DEFINE OFF;
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('1','100',to_date('14/11/19','DD/MM/RR'),to_date('16/11/19','DD/MM/RR'),to_date('16/12/19','DD/MM/RR'),'5','1','250');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('2','150',to_date('16/11/19','DD/MM/RR'),to_date('17/11/19','DD/MM/RR'),to_date('17/12/19','DD/MM/RR'),'4','2','300');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('3','200',to_date('12/11/19','DD/MM/RR'),to_date('15/11/19','DD/MM/RR'),to_date('15/12/19','DD/MM/RR'),'3','3','350');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('4','100',to_date('14/11/19','DD/MM/RR'),to_date('16/11/19','DD/MM/RR'),to_date('16/12/19','DD/MM/RR'),'2','4','250');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('5','150',to_date('16/11/19','DD/MM/RR'),to_date('16/11/19','DD/MM/RR'),to_date('16/12/19','DD/MM/RR'),'1','5','300');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('6','200',to_date('12/11/19','DD/MM/RR'),to_date('16/11/19','DD/MM/RR'),to_date('16/12/19','DD/MM/RR'),'10','6','350');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('7','100',to_date('14/11/19','DD/MM/RR'),to_date('16/11/19','DD/MM/RR'),to_date('16/12/19','DD/MM/RR'),'9','7','250');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('8','150',to_date('16/11/19','DD/MM/RR'),to_date('16/11/19','DD/MM/RR'),to_date('16/12/19','DD/MM/RR'),'8','8','300');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('9','200',to_date('12/11/19','DD/MM/RR'),to_date('15/11/19','DD/MM/RR'),to_date('15/12/19','DD/MM/RR'),'7','9','350');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('10','100',to_date('14/11/19','DD/MM/RR'),to_date('15/11/19','DD/MM/RR'),to_date('15/12/19','DD/MM/RR'),'6','10','250');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('11','150',to_date('16/11/19','DD/MM/RR'),to_date('15/11/19','DD/MM/RR'),to_date('15/12/19','DD/MM/RR'),'5','11','300');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('12','200',to_date('12/11/19','DD/MM/RR'),to_date('17/11/19','DD/MM/RR'),to_date('17/12/19','DD/MM/RR'),'4','12','350');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('13','100',to_date('14/11/19','DD/MM/RR'),to_date('17/11/19','DD/MM/RR'),to_date('17/12/19','DD/MM/RR'),'3','13','250');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('14','150',to_date('16/11/19','DD/MM/RR'),to_date('17/11/19','DD/MM/RR'),to_date('17/12/19','DD/MM/RR'),'2','14','300');
Insert into DEIVY1.ALQUILER (CODALQ,FIANALQ,FECFIRM,FECINI,FECFIN,CODINQ,CODVIV,IMPMENS) values ('15','200',to_date('12/11/19','DD/MM/RR'),to_date('15/11/19','DD/MM/RR'),to_date('15/12/19','DD/MM/RR'),'1','15','350');
--------------------------------------------------------
--  DDL for Index ALQUILER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEIVY1"."ALQUILER_PK" ON "DEIVY1"."ALQUILER" ("CODALQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ALQUILER
--------------------------------------------------------

  ALTER TABLE "DEIVY1"."ALQUILER" ADD CONSTRAINT "ALQUILER_PK" PRIMARY KEY ("CODALQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEIVY1"."ALQUILER" MODIFY ("IMPMENS" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."ALQUILER" MODIFY ("CODVIV" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."ALQUILER" MODIFY ("CODINQ" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."ALQUILER" MODIFY ("FECFIN" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."ALQUILER" MODIFY ("FECINI" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."ALQUILER" MODIFY ("FECFIRM" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."ALQUILER" MODIFY ("FIANALQ" NOT NULL ENABLE);
  ALTER TABLE "DEIVY1"."ALQUILER" MODIFY ("CODALQ" NOT NULL ENABLE);
