--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-14-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VIVIENDA
--------------------------------------------------------

  CREATE TABLE "DEIVY1"."VIVIENDA" 
   (	"CODVIV" NUMBER(4,0), 
	"CODPOST" NUMBER(5,0), 
	"POBVIV" NUMBER(4,0), 
	"CALLE" VARCHAR2(40 BYTE), 
	"NUMVIV" NUMBER(3,0), 
	"PISVIV" NUMBER(2,0), 
	"CODPRO" NUMBER(4,0), 
	"CODAGEN" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DEIVY1.VIVIENDA
SET DEFINE OFF;
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('1','15700','2','San Agustin','515','2','1',null);
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('2','15700','1','urb PRIMAVERA','500','2',null,'2');
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('3','15700','1','San Agustin','501','4','3',null);
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('4','15700','1','urb PRIMAVERA','502','3',null,'4');
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('5','15700','3','San Agustin','503','4','5',null);
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('6','15700','1','urb PRIMAVERA','504','4',null,'6');
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('7','15700','2','San Agustin','505','4','7',null);
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('8','15700','2','urb PRIMAVERA','506','2',null,'8');
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('9','15700','2','San Agustin','507','2','9',null);
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('10','15700','2','urb PRIMAVERA','508','2',null,'10');
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('11','15700','2','San Agustin','509','2','11',null);
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('12','15700','2','urb PRIMAVERA','510','3',null,'12');
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('13','15700','2','San Agustin','511','3','13',null);
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('14','15700','3','urb PRIMAVERA','512','3',null,'14');
Insert into DEIVY1.VIVIENDA (CODVIV,CODPOST,POBVIV,CALLE,NUMVIV,PISVIV,CODPRO,CODAGEN) values ('15','15700','3','San Agustin','513','4','15',null);
--------------------------------------------------------
--  DDL for Index VIVIENDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEIVY1"."VIVIENDA_PK" ON "DEIVY1"."VIVIENDA" ("CODVIV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VIVIENDA
--------------------------------------------------------

  ALTER TABLE "DEIVY1"."VIVIENDA" ADD CONSTRAINT "VIVIENDA_PK" PRIMARY KEY ("CODVIV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEIVY1"."VIVIENDA" MODIFY ("CODVIV" NOT NULL ENABLE);
